# -*- coding: utf-8 -*-
"""exemplo1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16RNLX5OL50LMWgY2nKD2Uaf6igY3A3P4
"""

ordem_execucao = []
print('O tipo da variável ordem_execucao é: ',type(ordem_execucao))
numero_celula = 1
ordem_execucao.append(numero_celula)
print(ordem_execucao)

numero_celula = 2
ordem_execucao.append(numero_celula)
print(ordem_execucao)

numero_celula = 3
ordem_execucao.append(numero_celula)
print(ordem_execucao)

numero_celula = 4
ordem_execucao.append(numero_celula)
print(ordem_execucao)

numero_celula = 5
ordem_execucao.append(numero_celula)
print(ordem_execucao)

numero_celula = 6
ordem_execucao.append(numero_celula)
print(ordem_execucao)

numero_celula = 7
ordem_execucao.append(numero_celula)
print(ordem_execucao)

numero_celula = 8
ordem_execucao.append(numero_celula)
print(ordem_execucao)

numero_celula = 9
ordem_execucao.append(numero_celula)
print(ordem_execucao)

numero_celula = 10
ordem_execucao.append(numero_celula)
print(ordem_execucao)

