# -*- coding: utf-8 -*-
"""exemplo2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11AdXvJyN_v5myg02kueCn1QRbSHamvVL
"""

#definindo o valor inicial
resultado = int(input("Digite o valor inicial: "))

#soma
resultado = resultado + int(input("Digite o valor a ser somado: "))

#subtração
resultado = resultado - int(input("Digite o valor a ser subtraído: "))

#multiplicação
resultado = resultado * int(input("Digite o valor do multiplicador: "))

#divisão
resultado = resultado / int(input("Digite o valor do divisor: "))

#arredondar
resultado = round(resultado, 2)

#exibir o resultado para o usuário
print('Resultado final: ', resultado)

